[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "common"
version = "0.1"
description = "Common utilities"
authors = [{name = "Bạn"}]
dependencies = []

[tool.setuptools.packages.find]
include = ["common", "common.*"]